using System.Net;

namespace packages.Api.Responses
{
    /// <summary>
    /// A simple machine-readable format for specifying errors in HTTP API responses<br />
    /// based on https://tools.ietf.org/html/rfc7807.
    /// </summary>
    public class ProblemDetailsSimple
    {
        /// <summary>
        /// A short, human-readable summary of the problem type.It SHOULD NOT change from
        /// occurrence to occurrence of the problem, except for purposes of localization(e.g.,
        /// using proactive content negotiation; see[RFC7231], Section 3.4).
        /// </summary>
        public string? Title { get; set; }

        /// <summary>
        /// The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
        /// </summary>
        public HttpStatusCode? Status { get; set; }

        /// <summary>
        /// A human-readable explanation specific to this occurrence of the problem.
        /// </summary>
        public string? Detail { get; set; }
    }
}
